name: justtalktoit
favicon: null
layout_spectrum: 0.026069281855598092
typography_spectrum: 0.5078769237734377
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.3803743254393339
  lightness: 0.6626108312048018
  saturation: 0.7530274202581495
  rhythmicContrast: 0.14186784415505826
purpose: []
